---
- name: get submodule status
  shell: git submodule status ../roles | cut -c1
  register: status

# This really should not be possible, because the `git pull` will have
# failed first.
- name: fail when a merge conflict exists
  fail:
    msg: >
      The roles submodule has merge conflicts and cannot be updated. Please
      stash any changes and resume them after provisioning.
  when: status.stdout == 'U'

# Otherwise, if the hash is prefixed with a “+” or “-”, it needs to be
# updated
- name: update the submodule
  command: git submodule update
  when: status.stdout in ['+', '-']
